name: workflows_service
env:
    cache-name: note
on:
   push:
        branches: 
            - main
        paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
          - README.md
          - package.json
   repository_dispatch:
        types: [my-event1,my-event2]
           
jobs:
    myEvent1:
      runs-on: ubuntu-latest
      name: service1 job
      steps:
          - uses: actions/checkout@v3
          - run: | 
               ls
               echo 'service1 job end'
    myEvent2:
      runs-on: ubuntu-latest
      name: service2 job
      steps:
          - uses: actions/checkout@v3
          - run: | 
               ls
               echo 'service2 job end'
          

        
